w2/app1/urls.py
from django.urls import path
from app1 import views
from django.contrib.auth.views import login_required

app_name = 'app1'
urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('code/', views.code, name='code'),
    path('login_pwd/', views.Login_in.as_view(), name='login_pwd'),
    path('login_code/', views.Login_code.as_view(), name='login_code'),
    # 登录装饰器   不登录不允许访问
    path('user_show/', login_required(views.user_show.as_view()), name='user_show'),
    path('login_out/', views.login_out, name='login_out'),

]

w2/w2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls'))
]

w2/app1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    phone = models.CharField(verbose_name='手机号', max_length=11)

    class Meta:
        db_table = 'user'

w2/app1/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views import View
import re, string, random
from app1.models import User
from django.core.cache import cache


# Create your views here.


class Register(View):
    def get(self, request):
        return render(request, 'app1/register.html')

    def post(self, request):
        phone = request.POST.get('phone')
        pwd1 = request.POST.get('pwd1')
        pwd2 = request.POST.get('pwd2')
        if re.match(r'1[3,4,5,7,8]\d{9}', phone):
            if pwd1 == pwd2:
                User.objects.create_user(username=phone,
                                         password=pwd2,
                                         phone=phone)
                return JsonResponse({'msg': '注册成功'})
            else:
                return JsonResponse({'msg': '2次密码输入不一样'})
        else:
            return JsonResponse({'msg': '手机号不合法'})


def code(request):
    """
    获取验证码
    :param request:
    :return:
    """
    # 1 获取手机号
    # phone = request.POST.get('phone')
    # 2 生成验证码
    code = ''.join(random.choices(string.digits, k=6))
    # 3 调用 第三方接口  发生验证码到手机号
    # aa(phone,code)
    # 4. 判断缓存是否有验证码
    if cache.has_key('code'):
        return JsonResponse({'msg': '请勿频繁发送验证码'})
    # 5 把验证码添加到缓存中
    else:
        cache.set('code', code, 60)
        return JsonResponse({'msg': '发送成功', 'code': code})


from django.contrib.auth import logout, login, authenticate


class Login_in(View):
    def get(self, request):
        """
        跳转页面
        :param request:
        :return:
        """
        return render(request, 'app1/login.html')

    def post(self, request):
        # 1 获取前段的数据
        phone = request.POST.get('phone')
        pwd1 = request.POST.get('pwd1')
        # 2 数据验证
        u = authenticate(username=phone, password=pwd1)
        print(phone, pwd1, u)
        if u:
            # 添加session
            login(request, u)
            return redirect('app1:user_show')
        else:
            return JsonResponse({'msg': '账号或者密码错误', 'code': 201})


class Login_code(View):
    def get(self, request):
        """
        跳转页面
        :param request:
        :return:
        """
        return render(request, 'app1/login_code.html')

    def post(self, request):
        # 1 获取前段的数据
        phone = request.POST.get('phone')
        s_code = request.POST.get('code')
        # 2 获取换成的验证码
        code = cache.get('code')
        # 2 数据验证
        u = User.objects.filter(username=phone).first()
        if u:
            if s_code == code:
                # 添加session
                login(request, u)
                return redirect('app1:user_show')
            else:
                return JsonResponse({'msg': '验证码输入错误', 'code': 200})
        else:
            # 没有账号  重定向到 注册页面
            return redirect('app1:register')


class user_show(View):
    def get(self, request):
        # 1. 获取所有的用用户信息
        info = User.objects.all().order_by('last_login')
        # 2. 返回页面
        # return render(request, 'app1/user_show.html', locals())
        return render(request, 'app1/user_show.html', context={'inof':info})


def login_out(request):
    # 退出
    logout(request)
    # 调整到登陆页面
    return redirect('app1:login_pwd')

w2/templates/app1/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="bs-example" data-example-id="basic-forms">
        <form id="form1" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">手机号</label>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="phone">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">密码</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"
                       name="pwd1">
            </div>
            <button type="submit" class="btn btn-default" id="but1">登陆</button>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        //函数的入库
        $(function () {
            //定义函数
            but1()
        })

        function but1() {
            // 点击登陆按钮的时候  执行一个函数
            $('#but1').click(function () {
                $.ajax({
                    'url': {% url 'app1:login_pwd' %},
                    'type': 'post',
                    'data': $('#form1').val(),
                    'dataType': 'JSON',
                    success: function (res) {
                        console.log(res)

                    }
                })

            })

        }

    </script>
{% endblock %}

w2/templates/app1/login_code.html
{% extends 'base.html' %}

{% block content %}
    <div class="bs-example" data-example-id="basic-forms">
        <form id="form1" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">手机号</label>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="phone">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">验证码</label>
                <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Password"
                       name="code">
            </div>
            <button type="submit" class="btn btn-default" id="but1">登陆</button>
        </form>
    </div>
    <a href="{% url 'app1:code' %}">发送验证码</a>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        //函数的入库
        $(function () {
            //定义函数
            but1()
        })

        function but1() {
            // 点击登陆按钮的时候  执行一个函数
            $('#but1').click(function () {
                $.ajax({
                    'url': {% url 'app1:login_code' %},
                    'type': 'post',
                    'data': $('#form1').val(),
                    'dataType': 'JSON',
                    success: function (res) {
                        console.log(res)

                    }
                })

            })

        }

    </script>
{% endblock %}

w2/templates/app1/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="bs-example" data-example-id="basic-forms">
        <form id="form1" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">手机号</label>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="phone">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">密码</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="pwd1">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">确认密码</label>
                <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password" name="pwd2">
            </div>
            <button type="submit" class="btn btn-default" id="but1">注册</button>
        </form>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(function () {
            //函数的入库
            but1()

        })

        function but1() {
            $('#but1').click(function () {

                $.ajax({
                    'url':{% url 'app1:register' %},
                    'type':'post',
                    'data':$('#form1').val(),
                    'dataType':'JSON',
                    success:function (res) {
                        console.log(res.msg)

                    }
                })

            })

        }

    </script>
{% endblock %}

w2/templates/app1/user_show.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <title>Title</title>
</head>
<body>
<div class="bs-example" data-example-id="simple-nav-pills">
    <ul class="nav nav-pills">
        <li role="presentation" class="active"><a href="{% url 'app1:login_out' %}">退出</a></li>
    </ul>
</div>

<div class="bs-example" data-example-id="bordered-table">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>用户名</th>
            <th>上次登陆时间</th>
        </tr>
        </thead>
        <tbody>
        {% for x in info %}
            <tr>
                <th scope="row">{{ x.id }}</th>
                <td>{{ x.username }}</td>
                <td>{{ x.last_login }}</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
</div>
</body>
</html>

w2/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    {% block css %}

    {% endblock %}
    <title>Title</title>
</head>
<body>
<div class="bs-example" data-example-id="simple-nav-pills">
    <ul class="nav nav-pills">
        <li role="presentation" class="active"><a href="{% url 'app1:login_pwd' %}">密码登陆</a></li>
        <li role="presentation"><a href="{% url 'app1:login_code' %}">验证登陆</a></li>
        <li role="presentation"><a href="{% url 'app1:register' %}">注册</a></li>
    </ul>
</div>
{% block content %}

{% endblock %}
<script src="/static/bootstrap/js/bootstrap.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/js/jquery.min.js"></script>
{% block js %}

{% endblock %}
</body>
</html>